;=========================================================
;= Refreshed Supply Pack v1.0                            =
;= Compilation by Akage Megane                           =
;= Initial Compilation : June 6, 2026                    =
;= https://github.com/akagemegane/RFS_RefreshedPack      =
;=========================================================

[EPISODE1]
Title = Community Maps
Map1 = DWBB1
Map2 = SIN
Map3 = DWBB2
Map4 = FUNERAL
Map5 = hotsteel
Map6 = masoleum
Map7 = melodies
Map8 = nrvhouse
Map9 = quakish
Map10 = JUDAS23S
Map11 = spaceshp
Map12 = WUDDAVOQ
Map13 = SHIPMENT
Map14 = B_DEPTH
Map15 = POOLDAZR
Map16 = biodanzR
Map17 = gunshop
Map18 = gripm
Map19 = facility
Map20 = xzone
Map21 = ultrav
Map22 = ssquake
Map23 = SHRINEM
Map24 = spillbb2
Map25 = #factory
Map26 = bodistoo
Map27 = jrbb10
Map28 = TOMBSM
Map29 = THEPARK
Map30 = AUTO46B
Map31 = BLOODRUN
Map32 = BLUDBANG
Map33 = bq3bb1_1
Map34 = b_Kefka
Map35 = b_SSL2
Map36 = iod2a
Map37 = HQBASEQ5
Map38 = $shotgun
Map39 = HOS-BB2
Map40 = CHURCH
Map41 = CITADELB
Map42 = d5m2
Map43 = BBevol1
Map44 = BB-CHAOS
Map45 = blfrenzy
Map46 = b_d5m1
Map47 = XNADM01

[EPISODE2]
Title = Community Maps (Large)
Map1 = BB3X
Map2 = BBHOUSE
Map3 = circense
Map4 = dwbb3
Map5 = MASSACRE
Map6 = BLACK
Map7 = 8-BALL

[EPISODE3]
Title = Community Maps (Teams)
Map1 = DWINTERM
Map2 = 2BASES
Map3 = bb3ct_10
Map4 = ssface
Map5 = 2-fort2

[EPISODE4]
Title = The Classics (Stock)
Map1 = bb1
Map2 = bb2
Map3 = bb3
Map4 = bb4
Map5 = bb5
Map6 = bb7
Map7 = bb8
Map8 = dm2
Map9 = dm3
Map10 = e6m8
Map11 = cpbb03
Map12 = E1M2
Map13 = E1M7
Map14 = cpbb04
Map15 = E4M8
Map16 = E2M2
Map17 = E2M8
Map18 = E4M9
Map19 = E6M1
Map20 = E1M4

[EPISODE5]
Title = Joke Maps
Map1 = BB-HELL3
Map2 = MINBODM
Map3 = LEDGESB1

;==============================================
;Episode 1: Community Maps
;==============================================

[DWBB1]
Title = Office Space (Death Wish, Dustin Twilley)
Author = DUSTIN TWILLEY

[SIN]
Title = Sin (Cho Yan Wong)
Author = Cho Yan Wong (Tempest)

[DWBB2]
Title = Rooftop Rumble (Death Wish, Dustin Twilley)
Author = DUSTIN TWILLEY

[FUNERAL]
Title = Funeral (Michael Ochs)
Author = MICHAEL OCHS

[hotsteel]
Title = Hot Steel (Tekedon)
Author = TEKEDON

[MASOLEUM]
Title = Masoleum (The Radish)
Author = The Radish

[melodies]
Title = Merry Melodies (Fernando Marquez)
Author = FERNANDO MÁRQUEZ

[nrvhouse]
Title = NRV House (Noldor Ranzou)

[quakish]
Title = Quakish (Pagb666)

[JUDAS23S]
Title = Judas23S (Sir Seizhak)

[spaceshp]
Title = Spaceship (ShadowWolf)

[WUDDAVOQ]
Title = Wuddavoq (BME/ILMHB)

[SHIPMENT]
Title = Shipment (Ocpjr)

[B_DEPTH]
Title = Depth (Sloth)

[POOLDAZR]
Title = Pool Day (Squall, Mundy)

[biodanzR]
Title = BiodanzR (IOD clan, Mundy)

[gunshop]
Title = Gunshop (Ocpjr)

[gripm]
Title = Grip (Chronic, Mundy)

[facility]
Title = Facility (Michael Ochs)

[xzone]
Title = XZone10 (Jet102)

[ultrav]
Title = UltraViolence (Escher, pagb666)

[ssquake]
Title = Arena Gate (SpillSomeBlood)

[SHRINEM]
Title = House of Wang (Mundy)

[spillbb2]
Title = Hangar (SpillSomeBlood)

[#factory]
Title = #Factory (Priest)

[bodistoo]
Title = Bodistoo (Unknown)

[jrbb10]
Title = jrbb10 (Ocpjr)

[TOMBSM]
Title = Wizard (Mundy)

[THEPARK]
Title = The Park (SpillSomeBlood)

[AUTO46B]
Title = Auto Tote (Nyyss0nen)

[BLOODRUN]
Title = Blood Run (Gary McLean)

[BLUDBANG]
Title = BloodBang (Tekedon)

[bq3bb1_1]
Title = Temple of Retribution (Unknown)

[b_Kefka]
Title = Kefka (Maligned)

[b_SSL2]
Title = SSL2 (Maligned)

[iod2a]
Title = IOD2A (IOD clan) 

[HQBASEQ5]
Title = HQ Base (Gunz)

[$shotgun]
Title = $Shotgun (Antonio Schaefer)

[HOS-BB2]
Title = Hostile Takeover 2 (Bloatoid)

[CHURCH]
Title = Church (Christian Schlaffer)

[CITADELB]
Title = Citadel (Unknown)

[d5m2]
Title = Dwango5 Map02 (Akage Megane)

[BBevol1]
Title = Evolution (sloth)

[BB-CHAOS]
Title = Chaos (Ocpjr)

[blfrenzy]
Title = Blood Frenzy (Maligned)

[b_d5m1]
Title = Dwango5 Map01 (Maligned)

[XNADM01]
Title = XNA Deathmatch (XNA)



;==============================================
;Episode 2: Community Maps (Large)
;==============================================

[BB3X]
Title = Bodies X (Slink)


[BBHOUSE]
Title = Abandoned House (Sir Seizhak)

[circense]
Title = Circense (Noldor Ranzou)

[dwbb3]
Title = Castle on the Coast (Dustin Twilley)

[MASSACRE]
Title = Massacre (Bradley Herr)

[BLACK]
Title = Black Study (Rune Trasop)

[8-BALL]
Title = 8-Ball (Noldor Ranzou)

;==============================================
;Episode 3: Community Maps (Teams)
;==============================================

[DWINTERM]
Title = Winter Wonderland (Teams) (Mundy)

[2BASES]
Title = 2Bases (Classic) (Nyyss0nen)

[bb3ct_10]
Title = Bodies (Teams) (Maligned)

[ssface]
Title = Facing Worlds (SpillSomeBlood)

[2-fort2]
Title = 2fort (Ocpjr)


;==============================================
;Episode 4: The Classics (Stock)
;==============================================

[BB1]
Title = The Stronghold (James Wilson)

[BB2]
Title = Winter Wonderland (James Wilson)

[bb3]
Title = Bodies (Craig Hubbard)

[bb4]
Title = The Tower (James Wilson)

[bb5]
Title = Click! (Kevin Kilstrom, Craig Hubbard)

[bb7]
Title = Midgard (Nick Newhard, Terry Hamel)

[bb8]
Title = Fun With Heads (James Wilson)

[dm2]
Title = Power! (Plasma Pak)

[dm3]
Title = Area 15 (Plasma Pak)

[e6m8]
Title = Beauty and the Beast (Nick Newhard, James Wilson)

[cpbb03]
Title = Unholy Cathedral (Sunstorm Interactive)

[E1M2]
Title = Wrong Side of The Tracks (Craig Hubbard)

[E1M4]
Title = Dark Carnival (Kevin Kilstrom, James Wilson)

[E1M7]
Title = Altar of Stone (James Wilson)

[cpbb04]
Title = Deadly Inspirations (Sunstorm Interactive)

[E4M8]
Title = The Hall of the Empiphany (Kevin Kilstrom)

[E2M2]
Title = The Lumber Mill (Craig Hubbard)

[E2M8]
Title = The Lair of Shial (James Wilson)

[E4M9]
Title = Mall of the Dead (Craig Hubbard)

[E6M1]
Title = Welcome To Your Life (James Wilson)


;==============================================
;Episode 5: Joke Maps
;==============================================
[BB-HELL3]
Title = Bloodbath Hell (Mean Mike T, Ocpjr)

[MINBODM]
Title = Mini Bodies (Mundy)

[LEDGESB1]
Title = Ledges (Unknown)
