;=========================================================
;= Refreshed Supply Pack v1.0.1                          =
;= Compilation by NerdBooba                              =
;= Initial Compilation : June 6, 2026                    =
;= https://github.com/akagemegane/RFS_RefreshedPack      =
;=========================================================

[EPISODE1]
Title = Community Maps
Map1 = #1
Map2 = #factory
Map3 = $shotgun
Map4 = AUTO46B
Map5 = b_d5m1
Map6 = B_DEPTH
Map7 = b_frz3a
Map8 = b_Kefka
Map9 = b_SSL2
Map10 = backyard
Map11 = BB-CHAOS
Map12 = BBevol1
Map13 = biodanzR
Map14 = Bjudas23
Map15 = blfrenzy
Map16 = BLOODRUN
Map17 = BLUDBANG
Map18 = bodistoo
Map19 = Body2012
Map20 = bq3bb1_1
Map21 = casadgc
Map22 = CHURCH
Map23 = CITADELB
Map24 = d5m2
Map25 = dogmeat
Map26 = Duke1
Map27 = DWBB1
Map28 = DWBB2
Map29 = facility
Map30 = FUNERAL
Map31 = gripm
Map32 = gunshop
Map33 = HOS-BB2
Map34 = hotsteel
Map35 = HQBASEQ5
Map36 = iod2a
Map37 = IODRPG13
Map38 = jrbb10
Map39 = JUDAS23S
Map40 = karnage3
Map41 = masoleum
Map42 = mbsewer
Map43 = melodies
Map44 = mlabrnt
Map45 = nrvhouse
Map46 = POOLDAZR
Map47 = q3dm3v3
Map48 = quake8
Map49 = quakish
Map50 = SHIPMENT
Map51 = SHRINEM
Map52 = SIN
Map53 = spaceshp
Map54 = spillbb2
Map55 = ssquake
Map56 = THEPARK
Map57 = TOMBSM
Map58 = Tower4b
Map59 = ultrav
Map60 = WHATEVER
Map61 = WHBB
Map62 = WUDDAVOQ
Map63 = XNADM01
Map64 = xzone

[EPISODE2]
Title = Community Maps (Large)
Map1 = 8-BALL
Map2 = BB3X
Map3 = BBHOUSE
Map4 = BLACK
Map5 = circense
Map6 = dwbb3
Map7 = MASSACRE

[EPISODE3]
Title = Community Maps (Teams)
Map1 = 2-fort2
Map2 = 2BASES
Map3 = bb3ct_10
Map4 = DM3T
Map5 = DWBB2T
Map6 = DWINTERM
Map7 = ssface

[EPISODE4]
Title = The Classics (Stock)
Map1 = bb1
Map2 = bb2
Map3 = bb3
Map4 = bb4
Map5 = bb5
Map6 = bb7
Map7 = bb8
Map8 = cpbb03
Map9 = cpbb04
Map10 = dm2
Map11 = dm3
Map12 = E1M1
Map13 = E1M2
Map14 = E1M3
Map15 = E1M4
Map16 = E1M7
Map17 = E2M2
Map18 = E2M8
Map19 = E4M8
Map20 = E4M9
Map21 = E6M1
Map22 = e6m8

[EPISODE5]
Title = Joke Maps
Map1 = BB-HELL3
Map2 = LEDGESB1
Map3 = MINBODM

;==============================================
;Episode 1: Community Maps
;==============================================

[DWBB1]
Title = Office Space (Death Wish, Bloatoid)

[SIN]
Title = Sin (Cho Yan Wong)

[DWBB2]
Title = Rooftop Rumble (Death Wish, Bloatoid)

[FUNERAL]
Title = Funeral (Michael Ochs)

[hotsteel]
Title = Hot Steel (Tekedon)

[MASOLEUM]
Title = Masoleum (The Radish)

[melodies]
Title = Merry Melodies (Fernando Marquez)

[nrvhouse]
Title = NRV House (Noldor Ranzou)

[quakish]
Title = Quakish (Pagb666)

[JUDAS23S]
Title = Judas23S (Sir Seizhak)

[spaceshp]
Title = Spaceship (ShadowWolf)

[WUDDAVOQ]
Title = Wuddavoq (BME/ILMHB)

[SHIPMENT]
Title = Shipment (Ocpjr)

[B_DEPTH]
Title = Depth (Sloth)

[POOLDAZR]
Title = Pool Day (Squall, Mundy)

[biodanzR]
Title = BiodanzR (IOD clan, Mundy)

[gunshop]
Title = Gunshop (Ocpjr)

[gripm]
Title = Grip (Chronic, Mundy)

[facility]
Title = Facility (Michael Ochs)

[xzone]
Title = XZone10 (Jet102)

[ultrav]
Title = UltraViolence (Escher, pagb666)

[ssquake]
Title = Arena Gate (SpillSomeBlood)

[SHRINEM]
Title = House of Wang (Mundy)

[spillbb2]
Title = Hangar (SpillSomeBlood)

[#factory]
Title = #Factory (Priest)

[bodistoo]
Title = Bodistoo (Unknown)

[jrbb10]
Title = jrbb10 (Ocpjr)

[TOMBSM]
Title = Wizard (Mundy)

[THEPARK]
Title = The Park (SpillSomeBlood)

[AUTO46B]
Title = Auto Tote (Nyyss0nen)

[BLOODRUN]
Title = Blood Run (Gary McLean)

[BLUDBANG]
Title = BloodBang (Tekedon)

[bq3bb1_1]
Title = Temple of Retribution (Unknown)

[b_Kefka]
Title = Kefka (Maligned)

[b_SSL2]
Title = SSL2 (Maligned)

[iod2a]
Title = IOD2A (IOD clan) 

[HQBASEQ5]
Title = HQ Base (Gunz)

[$shotgun]
Title = $Shotgun (Antonio Schaefer)

[HOS-BB2]
Title = Hostile Takeover 2 (Bloatoid)

[CHURCH]
Title = Church (Christian Schlaffer)

[CITADELB]
Title = Citadel (Unknown)

[d5m2]
Title = Dwango5 Map02 (NerdBooba)

[BBevol1]
Title = Evolution (sloth)

[BB-CHAOS]
Title = Chaos (Ocpjr)

[blfrenzy]
Title = Blood Frenzy (Maligned)

[b_d5m1]
Title = Dwango5 Map01 (Maligned)

[XNADM01]
Title = XNA Deathmatch (XNA)

[casadgc]
Title = Casadgc (Unknown)

[dogmeat]
Title = Dogmeat (Unknown)

[Duke1]
Title = Hollywood Holocaust (Unknown)

[karnage3]
Title = Karnage 3 (Unknown)

[mbsewer]
Title = Mbsewer (Unknown)

[mlabrnt]
Title = Mlabrnt (Unknown)

[q3dm3v3]
Title = Arena of Death (Gunz)

[quake8]
Title = Quake 8 (Shannon Savela)

[Body2012]
Title = Bodies 2012 (Unknown)

[IODRPG13]
Title = IODRPG13 (IOD clan)

[Bjudas23]
Title = Judas23 (Maligned)

[Tower4b]
Title = Tower4b (Nyyss0nen)

[WHATEVER]
Title = WHATEVER (B.M.E.)

[WHBB]
Title = WHBB (Unknown)

[#1]
Title = #1 (Unknown)

[b_frz3a]
Title = Frz3a (Unknown)

[backyard]
Title = Backyard (Unknown)

;==============================================
;Episode 2: Community Maps (Large)
;==============================================

[BB3X]
Title = Bodies X (Slink)


[BBHOUSE]
Title = Abandoned House (Sir Seizhak)

[circense]
Title = Circense (Noldor Ranzou)

[dwbb3]
Title = Castle on the Coast (Bloatoid)

[MASSACRE]
Title = Massacre (Bradley Herr)

[BLACK]
Title = Black Study (Rune Trasop)

[8-BALL]
Title = 8-Ball (Noldor Ranzou)

;==============================================
;Episode 3: Community Maps (Teams)
;==============================================

[DWINTERM]
Title = Winter Wonderland (Teams) (Mundy)

[2BASES]
Title = 2Bases (Classic) (Nyyss0nen)

[bb3ct_10]
Title = Bodies (Teams) (Maligned)

[ssface]
Title = Facing Worlds (SpillSomeBlood)

[2-fort2]
Title = 2Fort (Ocpjr)

[DM3T]
Title = Area 15 (Teams) (NerdBooba)

[DWBB2T]
Title = Rooftop Rumble (Teams) (Bloatoid, NerdBooba)


;==============================================
;Episode 4: The Classics (Stock)
;==============================================

[BB1]
Title = The Stronghold (James Wilson)

[BB2]
Title = Winter Wonderland (James Wilson)

[bb3]
Title = Bodies (Craig Hubbard)

[bb4]
Title = The Tower (James Wilson)

[bb5]
Title = Click! (Kevin Kilstrom, Craig Hubbard)

[bb7]
Title = Midgard (Nick Newhard, Terry Hamel)

[bb8]
Title = Fun With Heads (James Wilson)

[dm2]
Title = Power! (Plasma Pak)

[dm3]
Title = Area 15 (Plasma Pak)

[e6m8]
Title = Beauty and the Beast (Nick Newhard, James Wilson)

[cpbb03]
Title = Unholy Cathedral (Sunstorm Interactive)

[E1M1]
Title = Cradle to Grave (James Wilson)

[E1M2]
Title = Wrong Side of The Tracks (Craig Hubbard)

[E1M3]
Title = Phantom Express (James Wilson)

[E1M4]
Title = Dark Carnival (Kevin Kilstrom, James Wilson)

[E1M7]
Title = Altar of Stone (James Wilson)

[cpbb04]
Title = Deadly Inspirations (Sunstorm Interactive)

[E4M8]
Title = The Hall of the Empiphany (Kevin Kilstrom)

[E2M2]
Title = The Lumber Mill (Craig Hubbard)

[E2M8]
Title = The Lair of Shial (James Wilson)

[E4M9]
Title = Mall of the Dead (Craig Hubbard)

[E6M1]
Title = Welcome To Your Life (James Wilson)


;==============================================
;Episode 5: Joke Maps
;==============================================
[BB-HELL3]
Title = Bloodbath Hell (Mean Mike T, Ocpjr)

[MINBODM]
Title = Mini Bodies (Mundy)

[LEDGESB1]
Title = Ledges (Unknown)
